@startuml
!theme spacelab
skinparam DefaultTextAlignment center

start
:Поиск противника (Target),\nзаданного TargetSelector|
if (Target найден?) then (<color:black>да) 
    if (CustomConditions\nистины?) then (<color:black>да) 
        if(Target отличается\nот CurrentTarget ?) then (<color:black>да)
            :CurrentTarget := Target;
            end
        else (<color:black>нет) 
            end
        endif
    else (<color:black>нет) 
        end
    endif
else (<color:black>нет)
    end
endif

@enduml