@startuml
!theme spacelab
skinparam DefaultTextAlignment Center

start
repeat :Поиск Teammate\nс учетом CustomRegions|
if(Teammate найден ?) then (<color:black>да) 
    :Сборос таймера\nTeammateSearchTime]
    if(Расстояние до Teammate\nбольше CombatDistance ?) then (<color:black>да)
        if (Флаг IgnoreCombat = True) then (<color:black>да)
            :Снять запрет боя]
        else (<color:black>нет)
        endif
        :Перемещение к Teammate|
    else (<color:black>нет)
    endif
    :Поиск противника,\nзаданного FoePreference|
    if(Противник найден ?) then (<color:black>да)
        if(AbortCombatDistance > CombatDistance) then (<color:black>да)
            :Установить тригер\nпрерывания боя\nв случае превышения\nAbortCombatDistance]
        else (<color:black>нет)
        endif
        :Атаковать противника|
    else (<color:black>нет)
    endif

else (<color:black>нет)
    :Ждать 1 с.]
endif
repeat while (Флаг StopOnApproach = False\nИ\nTeammateSearchTime НЕ истек) is (<color:black>да)
stop

@enduml