@startuml
!theme spacelab
skinparam DefaultTextAlignment Center
'skinparam ConditionStyle InsideDiamond
'skinparam BackgroundColor White

start

repeat

'partition "Поиск" {
    while (Target отсутствует\nИЛИ\nИстекло время повторного поиска?) is (<color:black>да)

        :Поиск ближайшего Entity\n(ClosestEntity)|
        :Обновить время повторного поиска\n(EntityCacheTimer)]
        if (ClosestEntity найдено?) then (<color:black>да) 
            :Обновить таймер\nдо окончания поиска\n(EntitySearchTime)]
            if (Флаг HoldTargetEntity задан (True) ?) then (<color:black>да) 
            else (<color:black>нет)
                :Target := ClosestEntity|
            endif 
            if (Расстояние до ClosestEntity\nменьше CombatDistance ?) then (<color:black>да)
                (А)
            else (<color:black>нет)
                break
            endif
        else (<color:black>нет)
            if (Флаг IgnoreCombat задан (True)\nИ\nпроверка IngnoreCombatCondition истинна?) then (<color:black>да) 
                :Установка запрета боя \n и IgnoreCombatMinHP]
            else (<color:black>нет)
            endif
        endif
        ' if (Target отсутствует ?) then (<color:black>нет) 
        '     break
        ' else (<color:black>да)
        ' endif
        :Перемещение к\nследующему HotSpot|
    endwhile (<color:black>нет)
'}

'partition "Перемещение" {
if (Расстояние до Target\nбольше CombatDistance ?) then (<color:black>да)
    if (Флаг IgnoreCombat задан (True)\nИ\nпроверка IngnoreCombatCondition истинна?) then (<color:black>да) 
        :Установка запрета боя \n и IgnoreCombatMinHP]
    else (<color:black>нет)
    endif
    :Перемещение к Target|
else (<color:black>нет)
endif
'}

(А)

'partition "Бой" {
if (Задано PowerId) then (<color:black>да) 
    :Активация умения PowerId на Target]
else (<color:black>нет)
endif

if (Флаг IgnoreCombat задан (True)\nИ\nAbortCombatDistance > CombatDistance) then (<color:black>да) 
    :Установить тригер\nпрерывания боя\nв случае превышения\nAbortCombatDistance]
else (<color:black>нет)
endif

:Снять запрет боя]
if (Флаг АttackTargetEntity установлен (True) ?) then (<color:black>да)
    if(Расстояние до ClosestEntity\nменьше CombatDistance ?) then (<color:black>да)
        :Атаковать ClosestEntity|
    else (<color:black>нет)
    endif
    if(Расстояние до Target\nменьше CombatDistance ?) then (<color:black>да)
        :Атаковать Target|
    else (<color:black>нет)
    endif
else (<color:black>нет)
    :Атаковать произвольного\nврага|
endif
'}

repeat while (Флаг StopOnApproached не задан (False)\nИ\nвремя окончания поиска не закончилось\n(EntitySearchTime)) is (<color:black>да) 

stop

@enduml