@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam BackgroundColor transparent

AddElementTag("replaced", $fontColor="DarkOrange")
AddRelTag("replace", $textColor="DarkOrange", $lineColor="DarkOrange", $lineStyle = DashedLine())

AddElementTag("patched", $fontColor="DarkRed")
AddRelTag("patch", $textColor="Red", $lineColor="Red", $lineStyle = DashedLine())

System(nw, "Neverwinter", "Клиент MMORPG\n'Neverwinter Online'")

System_Boundary(bot, "Astral") {
    Container(myNW, "MyNW.dll", "Доступ к памяти игры и инъекции кода")

    myNW <<-up->> nw : "**Чтение и запись данных**\n//[Инъекции]//"

    Boundary(exe, "Astral.exe") {
        
        Container(quester, "Quester", "Скриптовая подсистема")
        quester <<-up->> myNW : "**'Взаимодействия'**\nОбмен командами и данными"

        Container(ucc, "UCC", "Боевая подсистема")
        ucc <<-up->> myNW : "**'Активация умений'**\nОбмен командами и данными"

        Container(nav, "Navigation", "Навигационная подсистема")
        nav <<-up->> myNW : "**'Перемещения'**\nОбмен командами и данными"

        quester <<-right->> nav : "Обмен командами\nи данными"
        nav <<-right->> ucc : "Обмен командами\nи данными"
    }

    Boundary(plugins, "Plugins") {
        Container(et, "EntityTools.dll", "Плагин")
        et -up->> ucc : "**Добавляет команды**\n**и условия**\n//[API]//"
        et -[#DarkRed;thickness=4]->> ucc #text:DarkRed : "**Патчит**\n//[Harmony]//"
        
        et -up->> quester : "**Добавляет команды**\n**и условия**\n//[API]//"
        et -[#DarkRed;thickness=4]->> quester #text:DarkRed : "**Патчит**\n//[Harmony]//"
        
        et -[#DarkRed;thickness=4]->> nav #text:DarkRed : "**Патчит**\n//[Harmony]//"
    }

    Lay_D(nav, et)
}

@enduml