@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("replaced", $fontColor="DarkOrange")
AddRelTag("replace", $textColor="DarkOrange", $lineColor="DarkOrange", $lineStyle = DashedLine())

AddElementTag("patched", $fontColor="DarkRed")
AddRelTag("patch", $textColor="Red", $lineColor="Red", $lineStyle = DashedLine())

System(nw, "Neverwinter", "Клиент MMORPG\n'Neverwinter Online'")

System_Boundary(c1, "Astral") {
    Container(amClient, "AMClient.dll", "Подключение к серверу", $tags="replaced")

    Boundary(c2, "Astral.exe") {
        Container(quester, "Quester", "Скриптовая подсистема")
        Rel_D(quester, nw, "Взаимодействия", "Инъекция")

        Container(ucc, "UCC", "Боевая подсистема", $tags="patched")
        Rel_R(ucc, nw, "Активация умений", "Инъекция")

        Lay_D(quester, ucc)

        Container(nav, "Navigation", "Навигационная подсистема", $tags="patched")

        Lay_D(ucc, nav)

        Rel_U(nav, nw, "Перемещения", "Инъекция")
    }
    
    Container(et, "EntityTools.dll", "Плагин")
    Rel_U(et, amClient, "Заменяет для внедрения патчей", $tags="replace")
    Rel_R(et, quester, "Добавляет команды и условия")
    Rel_R(et, ucc, "Добавляет команды и условия")

    Rel_D(et, ucc, "Патчит", $tags="patch")
    Rel_D(et, nav, "Патчит", $tags="patch")

    Container(aStar, "AStar.dll", "Поиск пути в графе", $tags="replaced")  
    Rel_R(aStar, nav, "Путевой граф")
    Rel_D(et, aStar, "Заменяет для расширения функциональности", $tags="replace")    
}

Person(botter, "Ботовод")
Rel_D(botter, nw, "Управляет", "GUI")

Rel_R(botter, quester, "Конфигурирует", "GUI")

@enduml